using System;
using System.Collections.Generic;

public static class SuspensionControlLimits
{
	static SuspensionControlLimits()
	{
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("AssetFrontSuspension", "Axis width", 0f, 0.15f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("AssetFrontSuspension", "Shocks offset", -0.1f, 0.1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("AssetFrontSuspension", "Shocks height", -0.05f, 0.1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("AssetFrontSuspension", "Middle frame width", 0f, 0.15f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("AssetFrontSuspension", "Axle type", 0f, 0f, 0f, 0, 1, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("AssetFrontSuspension", "Brake type", 0f, 0f, 0f, 0, 1, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("AssetFrontSuspension", "Show arms", 0f, 0f, 0f, 0, 1, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("AssetFrontSuspension", "Stiffness", 1000f, 50000f, 15000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("AssetFrontSuspension", "Damping", 100f, 10000f, 2000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("AssetFrontSuspension", "Travel", 0.1f, 0.7f, 0.3f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("AssetFrontSuspension", "Shocks size", 1f, 3f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("AssetFrontSuspension", "Shocks", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("AssetFrontSuspension", "Rim", 0f, 0f, 0f, 0, 8, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("AssetFrontSuspension", "Tire", 0f, 0f, 0f, 0, 7, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("AssetFrontSuspension", "Rim size", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("AssetFrontSuspension", "Wheels radius", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("AssetFrontSuspension", "Wheels width", 0.5f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("MonsterFrontSuspension", "Axis width", 0f, 0.07f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("MonsterFrontSuspension", "Stiffness", 8000f, 50000f, 15000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("MonsterFrontSuspension", "Damping", 100f, 10000f, 2000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("MonsterFrontSuspension", "Travel", 0.5f, 1.1f, 0.5f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("MonsterFrontSuspension", "Shocks size", 1f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("MonsterFrontSuspension", "Shocks", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("MonsterFrontSuspension", "Rim", 0f, 0f, 0f, 0, 8, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("MonsterFrontSuspension", "Tire", 0f, 0f, 0f, 0, 7, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("MonsterFrontSuspension", "Rim size", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("MonsterFrontSuspension", "Wheels radius", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("MonsterFrontSuspension", "Wheels width", 0.5f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("MonsterRearSuspension", "Axis width", 0f, 0.07f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("MonsterRearSuspension", "Rear steering", 0f, 1f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("MonsterRearSuspension", "Stiffness", 8000f, 50000f, 15000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("MonsterRearSuspension", "Damping", 100f, 10000f, 2000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("MonsterRearSuspension", "Travel", 0.5f, 1.1f, 0.5f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("MonsterRearSuspension", "Shocks size", 1f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("MonsterRearSuspension", "Shocks", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("MonsterRearSuspension", "Rim", 0f, 0f, 0f, 0, 8, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("MonsterRearSuspension", "Tire", 0f, 0f, 0f, 0, 7, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("MonsterRearSuspension", "Rim size", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("MonsterRearSuspension", "Wheels radius", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("MonsterRearSuspension", "Wheels width", 0.5f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("CrawlerSolidAxleFrontSuspension", "Axis width", 0f, 0.15f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("CrawlerSolidAxleFrontSuspension", "Axle type", 0f, 0f, 0f, 0, 1, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("CrawlerSolidAxleFrontSuspension", "Brake type", 0f, 0f, 0f, 0, 1, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("CrawlerSolidAxleFrontSuspension", "Rear steering", 0f, 1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("CrawlerSolidAxleFrontSuspension", "Stiffness", 1000f, 50000f, 20000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("CrawlerSolidAxleFrontSuspension", "Damping", 100f, 10000f, 1000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("CrawlerSolidAxleFrontSuspension", "Travel", 0.1f, 0.7f, 0.3f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("CrawlerSolidAxleFrontSuspension", "Shocks size", 1f, 3f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("CrawlerSolidAxleFrontSuspension", "Shocks", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("CrawlerSolidAxleFrontSuspension", "Rim", 0f, 0f, 0f, 0, 8, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("CrawlerSolidAxleFrontSuspension", "Tire", 0f, 0f, 0f, 0, 7, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("CrawlerSolidAxleFrontSuspension", "Rim size", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("CrawlerSolidAxleFrontSuspension", "Wheels radius", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("CrawlerSolidAxleFrontSuspension", "Wheels width", 0.5f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("CrawlerSolidAxleRearSuspension", "Axis width", 0f, 0.15f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("CrawlerSolidAxleRearSuspension", "Axle type", 0f, 0f, 0f, 0, 1, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("CrawlerSolidAxleRearSuspension", "Brake type", 0f, 0f, 0f, 0, 1, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("CrawlerSolidAxleRearSuspension", "Rear steering", 0f, 1f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("CrawlerSolidAxleRearSuspension", "Stiffness", 1000f, 50000f, 20000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("CrawlerSolidAxleRearSuspension", "Damping", 100f, 10000f, 1000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("CrawlerSolidAxleRearSuspension", "Travel", 0.1f, 0.7f, 0.3f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("CrawlerSolidAxleRearSuspension", "Shocks size", 1f, 3f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("CrawlerSolidAxleRearSuspension", "Shocks", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("CrawlerSolidAxleRearSuspension", "Rim", 0f, 0f, 0f, 0, 8, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("CrawlerSolidAxleRearSuspension", "Tire", 0f, 0f, 0f, 0, 7, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("CrawlerSolidAxleRearSuspension", "Rim size", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("CrawlerSolidAxleRearSuspension", "Wheels radius", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("CrawlerSolidAxleRearSuspension", "Wheels width", 0.5f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler2SolidAxleFrontSuspension", "Axis width", 0f, 0.15f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler2SolidAxleFrontSuspension", "Axle type", 0f, 0f, 0f, 0, 1, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler2SolidAxleFrontSuspension", "Brake type", 0f, 0f, 0f, 0, 1, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler2SolidAxleFrontSuspension", "Rear steering", 0f, 1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler2SolidAxleFrontSuspension", "Stiffness", 1000f, 50000f, 20000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler2SolidAxleFrontSuspension", "Damping", 100f, 10000f, 1000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler2SolidAxleFrontSuspension", "Travel", 0.1f, 0.7f, 0.3f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler2SolidAxleFrontSuspension", "Shocks size", 1f, 3f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler2SolidAxleFrontSuspension", "Shocks", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler2SolidAxleFrontSuspension", "Rim", 0f, 0f, 0f, 0, 8, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler2SolidAxleFrontSuspension", "Tire", 0f, 0f, 0f, 0, 7, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler2SolidAxleFrontSuspension", "Rim size", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler2SolidAxleFrontSuspension", "Wheels radius", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler2SolidAxleFrontSuspension", "Wheels width", 0.5f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler2SolidAxleRearSuspension", "Axis width", 0f, 0.15f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler2SolidAxleRearSuspension", "Axle type", 0f, 0f, 0f, 0, 1, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler2SolidAxleRearSuspension", "Brake type", 0f, 0f, 0f, 0, 1, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler2SolidAxleRearSuspension", "Rear steering", 0f, 1f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler2SolidAxleRearSuspension", "Stiffness", 1000f, 50000f, 20000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler2SolidAxleRearSuspension", "Damping", 100f, 10000f, 1000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler2SolidAxleRearSuspension", "Travel", 0.1f, 0.7f, 0.3f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler2SolidAxleRearSuspension", "Shocks size", 1f, 3f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler2SolidAxleRearSuspension", "Shocks", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler2SolidAxleRearSuspension", "Rim", 0f, 0f, 0f, 0, 8, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler2SolidAxleRearSuspension", "Tire", 0f, 0f, 0f, 0, 7, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler2SolidAxleRearSuspension", "Rim size", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler2SolidAxleRearSuspension", "Wheels radius", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler2SolidAxleRearSuspension", "Wheels width", 0.5f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3SolidAxleFrontSuspension", "Axis width", 0f, 0.15f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3SolidAxleFrontSuspension", "Axle type", 0f, 0f, 0f, 0, 1, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3SolidAxleFrontSuspension", "Brake type", 0f, 0f, 0f, 0, 1, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3SolidAxleFrontSuspension", "Rear steering", 0f, 1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3SolidAxleFrontSuspension", "Stiffness", 1000f, 50000f, 20000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3SolidAxleFrontSuspension", "Damping", 100f, 10000f, 1000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3SolidAxleFrontSuspension", "Travel", 0.1f, 0.7f, 0.3f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3SolidAxleFrontSuspension", "Shocks size", 1f, 3f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3SolidAxleFrontSuspension", "Shocks", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3SolidAxleFrontSuspension", "Rim", 0f, 0f, 0f, 0, 8, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3SolidAxleFrontSuspension", "Tire", 0f, 0f, 0f, 0, 7, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3SolidAxleFrontSuspension", "Rim size", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3SolidAxleFrontSuspension", "Wheels radius", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3SolidAxleFrontSuspension", "Wheels width", 0.5f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3SolidAxleRearSuspension", "Axis width", 0f, 0.15f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3SolidAxleRearSuspension", "Axle type", 0f, 0f, 0f, 0, 1, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3SolidAxleRearSuspension", "Brake type", 0f, 0f, 0f, 0, 1, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3SolidAxleRearSuspension", "Rear steering", 0f, 1f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3SolidAxleRearSuspension", "Stiffness", 1000f, 50000f, 20000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3SolidAxleRearSuspension", "Damping", 100f, 10000f, 1000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3SolidAxleRearSuspension", "Travel", 0.1f, 0.7f, 0.3f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3SolidAxleRearSuspension", "Shocks size", 1f, 3f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3SolidAxleRearSuspension", "Shocks", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3SolidAxleRearSuspension", "Rim", 0f, 0f, 0f, 0, 8, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3SolidAxleRearSuspension", "Tire", 0f, 0f, 0f, 0, 7, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3SolidAxleRearSuspension", "Rim size", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3SolidAxleRearSuspension", "Wheels radius", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3SolidAxleRearSuspension", "Wheels width", 0.5f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4SolidAxleFrontSuspension", "Axis width", 0f, 0.15f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4SolidAxleFrontSuspension", "Axle type", 0f, 0f, 0f, 0, 1, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4SolidAxleFrontSuspension", "Brake type", 0f, 0f, 0f, 0, 1, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4SolidAxleFrontSuspension", "Rear steering", 0f, 1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4SolidAxleFrontSuspension", "Stiffness", 1000f, 50000f, 20000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4SolidAxleFrontSuspension", "Damping", 100f, 10000f, 1000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4SolidAxleFrontSuspension", "Travel", 0.1f, 0.7f, 0.3f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4SolidAxleFrontSuspension", "Shocks size", 1f, 3f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4SolidAxleFrontSuspension", "Shocks", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4SolidAxleFrontSuspension", "Rim", 0f, 0f, 0f, 0, 8, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4SolidAxleFrontSuspension", "Tire", 0f, 0f, 0f, 0, 7, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4SolidAxleFrontSuspension", "Rim size", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4SolidAxleFrontSuspension", "Wheels radius", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4SolidAxleFrontSuspension", "Wheels width", 0.5f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4SolidAxleRearSuspension", "Axis width", 0f, 0.15f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4SolidAxleRearSuspension", "Axle type", 0f, 0f, 0f, 0, 1, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4SolidAxleRearSuspension", "Brake type", 0f, 0f, 0f, 0, 1, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4SolidAxleRearSuspension", "Rear steering", 0f, 1f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4SolidAxleRearSuspension", "Stiffness", 1000f, 50000f, 20000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4SolidAxleRearSuspension", "Damping", 100f, 10000f, 1000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4SolidAxleRearSuspension", "Travel", 0.1f, 0.7f, 0.3f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4SolidAxleRearSuspension", "Shocks size", 1f, 3f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4SolidAxleRearSuspension", "Shocks", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4SolidAxleRearSuspension", "Rim", 0f, 0f, 0f, 0, 8, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4SolidAxleRearSuspension", "Tire", 0f, 0f, 0f, 0, 7, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4SolidAxleRearSuspension", "Rim size", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4SolidAxleRearSuspension", "Wheels radius", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4SolidAxleRearSuspension", "Wheels width", 0.5f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler5SolidAxleFrontSuspension", "Axis width", 0f, 0.3f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler5SolidAxleFrontSuspension", "Axle type", 0f, 0f, 0f, 0, 1, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler5SolidAxleFrontSuspension", "Brake type", 0f, 0f, 0f, 0, 1, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler5SolidAxleFrontSuspension", "Rear steering", 0f, 1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler5SolidAxleFrontSuspension", "Stiffness", 1000f, 50000f, 20000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler5SolidAxleFrontSuspension", "Damping", 100f, 10000f, 1000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler5SolidAxleFrontSuspension", "Travel", 0.1f, 0.7f, 0.3f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler5SolidAxleFrontSuspension", "Shocks size", 1f, 3f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler5SolidAxleFrontSuspension", "Shocks", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler5SolidAxleFrontSuspension", "Rim", 0f, 0f, 0f, 0, 8, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler5SolidAxleFrontSuspension", "Tire", 0f, 0f, 0f, 0, 7, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler5SolidAxleFrontSuspension", "Rim size", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler5SolidAxleFrontSuspension", "Wheels radius", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler5SolidAxleFrontSuspension", "Wheels width", 0.5f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler5SolidAxleRearSuspension", "Axis width", 0f, 0.3f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler5SolidAxleRearSuspension", "Axle type", 0f, 0f, 0f, 0, 1, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler5SolidAxleRearSuspension", "Brake type", 0f, 0f, 0f, 0, 1, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler5SolidAxleRearSuspension", "Rear steering", 0f, 1f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler5SolidAxleRearSuspension", "Stiffness", 1000f, 50000f, 20000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler5SolidAxleRearSuspension", "Damping", 100f, 10000f, 1000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler5SolidAxleRearSuspension", "Travel", 0.1f, 0.7f, 0.3f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler5SolidAxleRearSuspension", "Shocks size", 1f, 3f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler5SolidAxleRearSuspension", "Shocks", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler5SolidAxleRearSuspension", "Rim", 0f, 0f, 0f, 0, 8, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler5SolidAxleRearSuspension", "Tire", 0f, 0f, 0f, 0, 7, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler5SolidAxleRearSuspension", "Rim size", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler5SolidAxleRearSuspension", "Wheels radius", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler5SolidAxleRearSuspension", "Wheels width", 0.5f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("IBeamFrontSuspension", "Axis width", 0f, 0.04f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("IBeamFrontSuspension", "Perch height", -0.05f, 0.1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("IBeamFrontSuspension", "Perch width", -0.05f, 0.1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("IBeamFrontSuspension", "Trailing arm mount width", -0.1f, 0.1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("IBeamFrontSuspension", "Stiffness", 1000f, 50000f, 20000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("IBeamFrontSuspension", "Damping", 100f, 10000f, 1000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("IBeamFrontSuspension", "Travel", 0.1f, 0.6f, 0.3f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("IBeamFrontSuspension", "Shocks size", 1f, 3f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("IBeamFrontSuspension", "Shocks", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("IBeamFrontSuspension", "Rim", 0f, 0f, 0f, 0, 8, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("IBeamFrontSuspension", "Tire", 0f, 0f, 0f, 0, 7, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("IBeamFrontSuspension", "Rim size", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("IBeamFrontSuspension", "Wheels radius", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("IBeamFrontSuspension", "Wheels width", 0.5f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("IndependentFrontSuspension", "AWD", 0f, 0f, 0f, 0, 1, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("IndependentFrontSuspension", "Axis width", 0f, 0.1f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("IndependentFrontSuspension", "Perch width", -0.03f, 0.1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("IndependentFrontSuspension", "Perch height", -0.05f, 0.05f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("IndependentFrontSuspension", "Stiffness", 1000f, 50000f, 20000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("IndependentFrontSuspension", "Damping", 100f, 10000f, 1000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("IndependentFrontSuspension", "Travel", 0.1f, 0.4f, 0.3f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("IndependentFrontSuspension", "Shocks size", 1f, 3f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("IndependentFrontSuspension", "Shocks", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("IndependentFrontSuspension", "Rim", 0f, 0f, 0f, 0, 8, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("IndependentFrontSuspension", "Tire", 0f, 0f, 0f, 0, 7, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("IndependentFrontSuspension", "Rim size", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("IndependentFrontSuspension", "Wheels radius", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("IndependentFrontSuspension", "Wheels width", 0.5f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("FordAFrontSuspension", "Axis width", 0f, 1f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("FordAFrontSuspension", "Stiffness", 1000f, 50000f, 20000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("FordAFrontSuspension", "Damping", 100f, 10000f, 1000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("FordAFrontSuspension", "Travel", 0.1f, 0.5f, 0.3f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("FordAFrontSuspension", "Shocks size", 1f, 3f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("FordAFrontSuspension", "Shocks", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("FordAFrontSuspension", "Rim", 0f, 0f, 0f, 0, 8, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("FordAFrontSuspension", "Tire", 0f, 0f, 0f, 0, 7, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("FordAFrontSuspension", "Rim size", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("FordAFrontSuspension", "Wheels radius", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("FordAFrontSuspension", "Wheels width", 0.5f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("TrophyFrontSuspension", "Axis width", 0f, 0.1f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("TrophyFrontSuspension", "Perch width", -0.02f, 0.1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("TrophyFrontSuspension", "Perch height", -0.05f, 0.05f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("TrophyFrontSuspension", "Stiffness", 1000f, 50000f, 20000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("TrophyFrontSuspension", "Damping", 100f, 10000f, 1000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("TrophyFrontSuspension", "Travel", 0.1f, 0.5f, 0.3f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("TrophyFrontSuspension", "Shocks size", 1f, 3f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("TrophyFrontSuspension", "Shocks", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("TrophyFrontSuspension", "Rim", 0f, 0f, 0f, 0, 8, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("TrophyFrontSuspension", "Tire", 0f, 0f, 0f, 0, 7, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("TrophyFrontSuspension", "Rim size", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("TrophyFrontSuspension", "Wheels radius", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("TrophyFrontSuspension", "Wheels width", 0.5f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3TrophyFrontSuspension", "Axis width", 0f, 0.1f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3TrophyFrontSuspension", "Perch width", -0.02f, 0.1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3TrophyFrontSuspension", "Perch height", -0.05f, 0.05f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3TrophyFrontSuspension", "Stiffness", 1000f, 50000f, 20000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3TrophyFrontSuspension", "Damping", 100f, 10000f, 1000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3TrophyFrontSuspension", "Travel", 0.1f, 0.5f, 0.3f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3TrophyFrontSuspension", "Shocks size", 1f, 3f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3TrophyFrontSuspension", "Shocks", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3TrophyFrontSuspension", "Rim", 0f, 0f, 0f, 0, 8, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3TrophyFrontSuspension", "Tire", 0f, 0f, 0f, 0, 7, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3TrophyFrontSuspension", "Rim size", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3TrophyFrontSuspension", "Wheels radius", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3TrophyFrontSuspension", "Wheels width", 0.5f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4TrophyFrontSuspension", "Axis width", 0f, 0.1f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4TrophyFrontSuspension", "Perch width", -0.02f, 0.1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4TrophyFrontSuspension", "Perch height", -0.05f, 0.05f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4TrophyFrontSuspension", "Stiffness", 1000f, 50000f, 20000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4TrophyFrontSuspension", "Damping", 100f, 10000f, 1000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4TrophyFrontSuspension", "Travel", 0.1f, 0.5f, 0.3f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4TrophyFrontSuspension", "Shocks size", 1f, 3f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4TrophyFrontSuspension", "Shocks", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4TrophyFrontSuspension", "Rim", 0f, 0f, 0f, 0, 8, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4TrophyFrontSuspension", "Tire", 0f, 0f, 0f, 0, 7, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4TrophyFrontSuspension", "Rim size", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4TrophyFrontSuspension", "Wheels radius", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4TrophyFrontSuspension", "Wheels width", 0.5f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("SolidAxleFrontSuspension", "Axis width", 0f, 0.1f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("SolidAxleFrontSuspension", "Frames width", -0.1f, 0.1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("SolidAxleFrontSuspension", "Front frame offset", -0.1f, 0.1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("SolidAxleFrontSuspension", "Rear frame offset", -0.1f, 0.1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("SolidAxleFrontSuspension", "Perch width", 0f, 0.1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("SolidAxleFrontSuspension", "Perch height", -0.05f, 0.1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("SolidAxleFrontSuspension", "Leaf spring mount height", -0.02f, 0.02f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("SolidAxleFrontSuspension", "Spring brackets upper mount", 0f, 0f, 0f, 0, 1, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("SolidAxleFrontSuspension", "Stiffness", 1000f, 50000f, 20000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("SolidAxleFrontSuspension", "Damping", 100f, 10000f, 1000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("SolidAxleFrontSuspension", "Travel", 0.1f, 0.7f, 0.3f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("SolidAxleFrontSuspension", "Shocks size", 1f, 3f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("SolidAxleFrontSuspension", "Shocks", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("SolidAxleFrontSuspension", "Rim", 0f, 0f, 0f, 0, 8, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("SolidAxleFrontSuspension", "Tire", 0f, 0f, 0f, 0, 7, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("SolidAxleFrontSuspension", "Rim size", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("SolidAxleFrontSuspension", "Wheels radius", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("SolidAxleFrontSuspension", "Wheels width", 0.5f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("SolidAxleRearSuspension", "Axis width", 0f, 0.1f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("SolidAxleRearSuspension", "Rear steering", 0f, 1f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("SolidAxleRearSuspension", "Frames width", -0.1f, 0.1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("SolidAxleRearSuspension", "Front frame offset", -0.1f, 0.1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("SolidAxleRearSuspension", "Rear frame offset", -0.1f, 0.1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("SolidAxleRearSuspension", "Shocks height", -0.05f, 0.1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("SolidAxleRearSuspension", "Shocks offset", -0.2f, 0.2f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("SolidAxleRearSuspension", "Leaf spring mount height", -0.02f, 0.02f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("SolidAxleRearSuspension", "Spring brackets upper mount", 0f, 0f, 0f, 0, 1, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("SolidAxleRearSuspension", "Stiffness", 1000f, 50000f, 20000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("SolidAxleRearSuspension", "Damping", 100f, 10000f, 1000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("SolidAxleRearSuspension", "Travel", 0.1f, 0.7f, 0.3f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("SolidAxleRearSuspension", "Shocks size", 1f, 3f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("SolidAxleRearSuspension", "Shocks", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("SolidAxleRearSuspension", "Rim", 0f, 0f, 0f, 0, 8, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("SolidAxleRearSuspension", "Tire", 0f, 0f, 0f, 0, 7, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("SolidAxleRearSuspension", "Rim size", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("SolidAxleRearSuspension", "Wheels radius", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("SolidAxleRearSuspension", "Wheels width", 0.5f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DoubleSolidAxleRearSuspension", "Axis width", 0f, 0.1f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DoubleSolidAxleRearSuspension", "Rear steering", 0f, 1f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DoubleSolidAxleRearSuspension", "Frames width", -0.1f, 0.1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DoubleSolidAxleRearSuspension", "Shocks height", -0.05f, 0.1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DoubleSolidAxleRearSuspension", "Shocks offset", -0.2f, 0.2f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DoubleSolidAxleRearSuspension", "Leaf spring mount height", -0.02f, 0.02f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DoubleSolidAxleRearSuspension", "Spring brackets upper mount", 0f, 0f, 0f, 0, 1, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DoubleSolidAxleRearSuspension", "Stiffness", 1000f, 50000f, 20000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DoubleSolidAxleRearSuspension", "Damping", 100f, 10000f, 1000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DoubleSolidAxleRearSuspension", "Travel", 0.1f, 0.7f, 0.3f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DoubleSolidAxleRearSuspension", "Shocks size", 1f, 3f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DoubleSolidAxleRearSuspension", "Shocks", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DoubleSolidAxleRearSuspension", "Rim", 0f, 0f, 0f, 0, 8, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DoubleSolidAxleRearSuspension", "Tire", 0f, 0f, 0f, 0, 7, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DoubleSolidAxleRearSuspension", "Rim size", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DoubleSolidAxleRearSuspension", "Wheels radius", 0.5f, 1.3f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DoubleSolidAxleRearSuspension", "Wheels width", 0.5f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ShamanRearSuspension", "Axis width", 0.03f, 0.1f, 0.05f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ShamanRearSuspension", "Rear steering", 0f, 1f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ShamanRearSuspension", "Frames width", -0.1f, 0.1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ShamanRearSuspension", "Shocks height", -0.05f, 0.1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ShamanRearSuspension", "Shocks offset", -0.2f, 0.2f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ShamanRearSuspension", "Leaf spring mount height", -0.02f, 0.02f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ShamanRearSuspension", "Spring brackets upper mount", 0f, 0f, 0f, 0, 1, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ShamanRearSuspension", "Stiffness", 1000f, 50000f, 20000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ShamanRearSuspension", "Damping", 100f, 10000f, 1000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ShamanRearSuspension", "Travel", 0.1f, 0.7f, 0.3f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ShamanRearSuspension", "Shocks size", 1f, 3f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ShamanRearSuspension", "Shocks", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ShamanRearSuspension", "Rim", 0f, 0f, 0f, 0, 8, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ShamanRearSuspension", "Tire", 0f, 0f, 0f, 0, 7, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ShamanRearSuspension", "Rim size", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ShamanRearSuspension", "Wheels radius", 0.5f, 1.3f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ShamanRearSuspension", "Wheels width", 0.5f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ShamanFrontSuspension", "Axis width", 0.03f, 0.1f, 0.05f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ShamanFrontSuspension", "Frames width", -0.1f, 0.1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ShamanFrontSuspension", "Front frame offset", -0.1f, 0.1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ShamanFrontSuspension", "Rear frame offset", -0.1f, 0.1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ShamanFrontSuspension", "Perch width", 0f, 0.1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ShamanFrontSuspension", "Perch height", -0.05f, 0.1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ShamanFrontSuspension", "Leaf spring mount height", -0.02f, 0.02f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ShamanFrontSuspension", "Spring brackets upper mount", 0f, 0f, 0f, 0, 1, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ShamanFrontSuspension", "Stiffness", 1000f, 50000f, 20000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ShamanFrontSuspension", "Damping", 100f, 10000f, 1000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ShamanFrontSuspension", "Travel", 0.1f, 0.7f, 0.3f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ShamanFrontSuspension", "Shocks size", 1f, 3f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ShamanFrontSuspension", "Shocks", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ShamanFrontSuspension", "Rim", 0f, 0f, 0f, 0, 8, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ShamanFrontSuspension", "Tire", 0f, 0f, 0f, 0, 7, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ShamanFrontSuspension", "Rim size", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ShamanFrontSuspension", "Wheels radius", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ShamanFrontSuspension", "Wheels width", 0.5f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("AssetRearSuspension", "Axis width", 0f, 0.15f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("AssetRearSuspension", "Shocks offset", -0.1f, 0.1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("AssetRearSuspension", "Shocks height", -0.05f, 0.1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("AssetRearSuspension", "Middle frame width", 0f, 0.15f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("AssetRearSuspension", "Rear steering", 0f, 1f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("AssetRearSuspension", "Axle type", 0f, 0f, 0f, 0, 1, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("AssetRearSuspension", "Brake type", 0f, 0f, 0f, 0, 1, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("AssetRearSuspension", "Show arms", 0f, 0f, 0f, 0, 1, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("AssetRearSuspension", "Stiffness", 1000f, 50000f, 20000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("AssetRearSuspension", "Damping", 100f, 10000f, 1000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("AssetRearSuspension", "Travel", 0.1f, 0.7f, 0.3f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("AssetRearSuspension", "Shocks size", 1f, 3f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("AssetRearSuspension", "Shocks", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("AssetRearSuspension", "Rim", 0f, 0f, 0f, 0, 8, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("AssetRearSuspension", "Tire", 0f, 0f, 0f, 0, 7, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("AssetRearSuspension", "Rim size", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("AssetRearSuspension", "Wheels radius", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("AssetRearSuspension", "Wheels width", 0.5f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("TrophyRearSuspension", "Axis width", 0f, 0.1f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("TrophyRearSuspension", "Rear steering", 0f, 1f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("TrophyRearSuspension", "Shocks offset", -0.1f, 0.1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("TrophyRearSuspension", "Shocks height", -0.05f, 0.05f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("TrophyRearSuspension", "Trailing arms offset", -0.1f, 0.1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("TrophyRearSuspension", "Trailing arms height", -0.1f, 0.1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("TrophyRearSuspension", "Stiffness", 1000f, 50000f, 20000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("TrophyRearSuspension", "Damping", 100f, 10000f, 1000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("TrophyRearSuspension", "Travel", 0.1f, 0.7f, 0.3f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("TrophyRearSuspension", "Shocks size", 1f, 3f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("TrophyRearSuspension", "Shocks", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("TrophyRearSuspension", "Rim", 0f, 0f, 0f, 0, 8, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("TrophyRearSuspension", "Tire", 0f, 0f, 0f, 0, 7, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("TrophyRearSuspension", "Rim size", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("TrophyRearSuspension", "Wheels radius", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("TrophyRearSuspension", "Wheels width", 0.5f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3TrophyRearSuspension", "Axis width", 0f, 0.1f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3TrophyRearSuspension", "Rear steering", 0f, 1f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3TrophyRearSuspension", "Shocks offset", -0.1f, 0.1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3TrophyRearSuspension", "Shocks height", -0.05f, 0.05f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3TrophyRearSuspension", "Trailing arms offset", -0.1f, 0.1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3TrophyRearSuspension", "Trailing arms height", -0.1f, 0.1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3TrophyRearSuspension", "Stiffness", 1000f, 50000f, 20000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3TrophyRearSuspension", "Damping", 100f, 10000f, 1000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3TrophyRearSuspension", "Travel", 0.1f, 0.7f, 0.3f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3TrophyRearSuspension", "Shocks size", 1f, 3f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3TrophyRearSuspension", "Shocks", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3TrophyRearSuspension", "Rim", 0f, 0f, 0f, 0, 8, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3TrophyRearSuspension", "Tire", 0f, 0f, 0f, 0, 7, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3TrophyRearSuspension", "Rim size", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3TrophyRearSuspension", "Wheels radius", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler3TrophyRearSuspension", "Wheels width", 0.5f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4TrophyRearSuspension", "Axis width", 0f, 0.1f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4TrophyRearSuspension", "Rear steering", 0f, 1f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4TrophyRearSuspension", "Shocks offset", -0.1f, 0.1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4TrophyRearSuspension", "Shocks height", -0.05f, 0.05f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4TrophyRearSuspension", "Trailing arms offset", -0.1f, 0.1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4TrophyRearSuspension", "Trailing arms height", -0.1f, 0.1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4TrophyRearSuspension", "Stiffness", 1000f, 50000f, 20000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4TrophyRearSuspension", "Damping", 100f, 10000f, 1000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4TrophyRearSuspension", "Travel", 0.1f, 0.7f, 0.3f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4TrophyRearSuspension", "Shocks size", 1f, 3f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4TrophyRearSuspension", "Shocks", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4TrophyRearSuspension", "Rim", 0f, 0f, 0f, 0, 8, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4TrophyRearSuspension", "Tire", 0f, 0f, 0f, 0, 7, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4TrophyRearSuspension", "Rim size", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4TrophyRearSuspension", "Wheels radius", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("Crawler4TrophyRearSuspension", "Wheels width", 0.5f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DragATVFrontSuspension", "Axis width", 0f, 0.2f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DragATVFrontSuspension", "Stiffness", 1000f, 50000f, 20000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DragATVFrontSuspension", "Damping", 100f, 10000f, 1000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DragATVFrontSuspension", "Travel", 0.1f, 0.4f, 0.2f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DragATVFrontSuspension", "Shocks size", 1f, 3f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DragATVFrontSuspension", "Shocks", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DragATVFrontSuspension", "Rim", 0f, 0f, 0f, 0, 3, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DragATVFrontSuspension", "Tire", 0f, 0f, 0f, 0, 7, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DragATVFrontSuspension", "Rim size", 0.5f, 1.5f, 1f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DragATVFrontSuspension", "Wheels radius", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DragATVFrontSuspension", "Wheels width", 0.5f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DragATVRearSuspension", "Axis width", 0f, 0.4f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DragATVRearSuspension", "Rear axle offset", -0.5f, 0.5f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DragATVRearSuspension", "Shock ups height", -0.1f, 0.1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DragATVRearSuspension", "Stiffness", 1000f, 50000f, 20000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DragATVRearSuspension", "Damping", 100f, 10000f, 1000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DragATVRearSuspension", "Travel", 0.1f, 0.4f, 0.2f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DragATVRearSuspension", "Shocks size", 1f, 3f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DragATVRearSuspension", "Shocks", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DragATVRearSuspension", "Rim", 0f, 0f, 0f, 0, 3, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DragATVRearSuspension", "Tire", 0f, 0f, 0f, 0, 7, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DragATVRearSuspension", "Rim size", 0.5f, 1.5f, 1f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DragATVRearSuspension", "Wheels radius", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DragATVRearSuspension", "Wheels width", 0.5f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("YamahaATVFrontSuspension", "Axis width", 0f, 0.2f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("YamahaATVFrontSuspension", "Stiffness", 1000f, 50000f, 20000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("YamahaATVFrontSuspension", "Damping", 100f, 10000f, 1000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("YamahaATVFrontSuspension", "Travel", 0.1f, 0.4f, 0.2f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("YamahaATVFrontSuspension", "Shocks size", 1f, 3f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("YamahaATVFrontSuspension", "Shocks", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("YamahaATVFrontSuspension", "Rim", 0f, 0f, 0f, 0, 3, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("YamahaATVFrontSuspension", "Tire", 0f, 0f, 0f, 0, 7, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("YamahaATVFrontSuspension", "Rim size", 0.5f, 1.5f, 1f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("YamahaATVFrontSuspension", "Wheels radius", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("YamahaATVFrontSuspension", "Wheels width", 0.5f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("YamahaATVRearSuspension", "Axis width", 0f, 0.2f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("YamahaATVRearSuspension", "Rear axle offset", 0f, 0.4f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("YamahaATVRearSuspension", "Shock ups height", -0.1f, 0.1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("YamahaATVRearSuspension", "Shock ups offset", -0.1f, 0.1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("YamahaATVRearSuspension", "Stiffness", 1000f, 50000f, 20000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("YamahaATVRearSuspension", "Damping", 100f, 10000f, 1000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("YamahaATVRearSuspension", "Travel", 0.1f, 0.4f, 0.2f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("YamahaATVRearSuspension", "Shocks size", 1f, 3f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("YamahaATVRearSuspension", "Shocks", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("YamahaATVRearSuspension", "Rim", 0f, 0f, 0f, 0, 3, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("YamahaATVRearSuspension", "Tire", 0f, 0f, 0f, 0, 7, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("YamahaATVRearSuspension", "Rim size", 0.5f, 1.5f, 1f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("YamahaATVRearSuspension", "Wheels radius", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("YamahaATVRearSuspension", "Wheels width", 0.5f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("PolarisUTVFrontSuspension", "Axis width", 0f, 0.4f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("PolarisUTVFrontSuspension", "Stiffness", 1000f, 50000f, 20000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("PolarisUTVFrontSuspension", "Damping", 100f, 10000f, 1000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("PolarisUTVFrontSuspension", "Travel", 0.1f, 0.4f, 0.2f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("PolarisUTVFrontSuspension", "Shocks size", 1f, 3f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("PolarisUTVFrontSuspension", "Shocks", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("PolarisUTVFrontSuspension", "Rim", 0f, 0f, 0f, 0, 3, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("PolarisUTVFrontSuspension", "Tire", 0f, 0f, 0f, 0, 7, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("PolarisUTVFrontSuspension", "Rim size", 0.5f, 1.5f, 1f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("PolarisUTVFrontSuspension", "Wheels radius", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("PolarisUTVFrontSuspension", "Wheels width", 0.5f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("PolarisUTVRearSuspension", "Axis width", 0f, 0.4f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("PolarisUTVRearSuspension", "Axis offset", 0f, 0.4f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("PolarisUTVRearSuspension", "Stiffness", 1000f, 50000f, 20000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("PolarisUTVRearSuspension", "Damping", 100f, 10000f, 1000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("PolarisUTVRearSuspension", "Travel", 0.1f, 0.4f, 0.2f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("PolarisUTVRearSuspension", "Shocks size", 1f, 3f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("PolarisUTVRearSuspension", "Shocks", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("PolarisUTVRearSuspension", "Rim", 0f, 0f, 0f, 0, 3, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("PolarisUTVRearSuspension", "Tire", 0f, 0f, 0f, 0, 7, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("PolarisUTVRearSuspension", "Rim size", 0.5f, 1.5f, 1f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("PolarisUTVRearSuspension", "Wheels radius", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("PolarisUTVRearSuspension", "Wheels width", 0.5f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("BugFrontSuspension", "Axis width", 0f, 0.3f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("BugFrontSuspension", "Stiffness", 1000f, 50000f, 20000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("BugFrontSuspension", "Damping", 100f, 10000f, 1000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("BugFrontSuspension", "Travel", 0.1f, 0.5f, 0.3f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("BugFrontSuspension", "Shocks size", 1f, 3f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("BugFrontSuspension", "Shocks", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("BugFrontSuspension", "Rim", 0f, 0f, 0f, 0, 3, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("BugFrontSuspension", "Tire", 0f, 0f, 0f, 0, 7, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("BugFrontSuspension", "Rim size", 0.5f, 1.5f, 1f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("BugFrontSuspension", "Wheels radius", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("BugFrontSuspension", "Wheels width", 0.5f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("BugRearSuspension", "Axis width", 0f, 0.4f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("BugRearSuspension", "Axis offset", 0f, 0.4f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("BugRearSuspension", "Stiffness", 1000f, 50000f, 20000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("BugRearSuspension", "Damping", 100f, 10000f, 1000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("BugRearSuspension", "Travel", 0.1f, 0.5f, 0.3f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("BugRearSuspension", "Shocks size", 1f, 3f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("BugRearSuspension", "Shocks", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("BugRearSuspension", "Rim", 0f, 0f, 0f, 0, 3, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("BugRearSuspension", "Tire", 0f, 0f, 0f, 0, 7, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("BugRearSuspension", "Rim size", 0.5f, 1.5f, 1f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("BugRearSuspension", "Wheels radius", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("BugRearSuspension", "Wheels width", 0.5f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("YFZ1000RUTVFrontSuspension", "Axis width", 0f, 0.4f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("YFZ1000RUTVFrontSuspension", "Stiffness", 1000f, 50000f, 20000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("YFZ1000RUTVFrontSuspension", "Damping", 100f, 10000f, 1000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("YFZ1000RUTVFrontSuspension", "Travel", 0.1f, 0.4f, 0.3f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("YFZ1000RUTVFrontSuspension", "Shocks size", 1f, 3f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("YFZ1000RUTVFrontSuspension", "Shocks", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("YFZ1000RUTVFrontSuspension", "Rim", 0f, 0f, 0f, 0, 3, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("YFZ1000RUTVFrontSuspension", "Tire", 0f, 0f, 0f, 0, 7, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("YFZ1000RUTVFrontSuspension", "Rim size", 0.5f, 1.5f, 1f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("YFZ1000RUTVFrontSuspension", "Wheels radius", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("YFZ1000RUTVFrontSuspension", "Wheels width", 0.5f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("YFZ1000UTVRearSuspension", "Axis width", 0f, 0.4f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("YFZ1000UTVRearSuspension", "Axis offset", 0f, 0.4f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("YFZ1000UTVRearSuspension", "Stiffness", 1000f, 50000f, 20000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("YFZ1000UTVRearSuspension", "Damping", 100f, 10000f, 1000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("YFZ1000UTVRearSuspension", "Travel", 0.1f, 0.4f, 0.3f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("YFZ1000UTVRearSuspension", "Shocks size", 1f, 3f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("YFZ1000UTVRearSuspension", "Shocks", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("YFZ1000UTVRearSuspension", "Rim", 0f, 0f, 0f, 0, 3, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("YFZ1000UTVRearSuspension", "Tire", 0f, 0f, 0f, 0, 7, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("YFZ1000UTVRearSuspension", "Rim size", 0.5f, 1.5f, 1f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("YFZ1000UTVRearSuspension", "Wheels radius", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("YFZ1000UTVRearSuspension", "Wheels width", 0.5f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV4FrontSuspension", "Axis width", 0f, 0.2f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV4FrontSuspension", "Stiffness", 1000f, 50000f, 20000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV4FrontSuspension", "Damping", 100f, 10000f, 1000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV4FrontSuspension", "Travel", 0.1f, 0.4f, 0.2f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV4FrontSuspension", "Shocks size", 1f, 3f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV4FrontSuspension", "Shocks", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV4FrontSuspension", "Rim", 0f, 0f, 0f, 0, 3, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV4FrontSuspension", "Tire", 0f, 0f, 0f, 0, 7, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV4FrontSuspension", "Rim size", 0.5f, 1.5f, 1f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV4FrontSuspension", "Wheels radius", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV4FrontSuspension", "Wheels width", 0.5f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV4RearSuspension", "Axis width", 0f, 0.2f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV4RearSuspension", "Rear axle offset", 0f, 0.4f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV4RearSuspension", "Shock ups height", -0.1f, 0.1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV4RearSuspension", "Shock ups offset", -0.1f, 0.1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV4RearSuspension", "Stiffness", 1000f, 50000f, 20000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV4RearSuspension", "Damping", 100f, 10000f, 1000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV4RearSuspension", "Travel", 0.1f, 0.4f, 0.2f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV4RearSuspension", "Shocks size", 1f, 3f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV4RearSuspension", "Shocks", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV4RearSuspension", "Rim", 0f, 0f, 0f, 0, 3, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV4RearSuspension", "Tire", 0f, 0f, 0f, 0, 7, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV4RearSuspension", "Rim size", 0.5f, 1.5f, 1f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV4RearSuspension", "Wheels radius", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV4RearSuspension", "Wheels width", 0.5f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV5FrontSuspension", "Axis width", 0f, 0.2f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV5FrontSuspension", "Stiffness", 1000f, 50000f, 20000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV5FrontSuspension", "Damping", 100f, 10000f, 1000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV5FrontSuspension", "Travel", 0.1f, 0.3f, 0.2f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV5FrontSuspension", "Shocks size", 1f, 3f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV5FrontSuspension", "Shocks", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV5FrontSuspension", "Rim", 0f, 0f, 0f, 0, 3, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV5FrontSuspension", "Tire", 0f, 0f, 0f, 0, 7, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV5FrontSuspension", "Rim size", 0.5f, 1.5f, 1f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV5FrontSuspension", "Wheels radius", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV5FrontSuspension", "Wheels width", 0.5f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV5RearSuspension", "Axis width", 0f, 0.2f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV5RearSuspension", "Rear axle offset", 0f, 0.4f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV5RearSuspension", "Shock ups height", -0.1f, 0.1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV5RearSuspension", "Shock ups offset", -0.1f, 0.1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV5RearSuspension", "Stiffness", 1000f, 50000f, 20000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV5RearSuspension", "Damping", 100f, 10000f, 1000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV5RearSuspension", "Travel", 0.1f, 0.3f, 0.2f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV5RearSuspension", "Shocks size", 1f, 3f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV5RearSuspension", "Shocks", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV5RearSuspension", "Rim", 0f, 0f, 0f, 0, 3, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV5RearSuspension", "Tire", 0f, 0f, 0f, 0, 7, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV5RearSuspension", "Rim size", 0.5f, 1.5f, 1f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV5RearSuspension", "Wheels radius", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV5RearSuspension", "Wheels width", 0.5f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV1FrontSuspension", "Axis width", 0f, 0.2f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV1FrontSuspension", "Stiffness", 1000f, 50000f, 20000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV1FrontSuspension", "Damping", 100f, 10000f, 1000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV1FrontSuspension", "Travel", 0.1f, 0.4f, 0.2f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV1FrontSuspension", "Shocks size", 1f, 3f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV1FrontSuspension", "Shocks", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV1FrontSuspension", "Rim", 0f, 0f, 0f, 0, 3, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV1FrontSuspension", "Tire", 0f, 0f, 0f, 0, 7, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV1FrontSuspension", "Rim size", 0.5f, 1.5f, 1f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV1FrontSuspension", "Wheels radius", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV1FrontSuspension", "Wheels width", 0.5f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV1RearSuspension", "Axis width", 0f, 0.2f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV1RearSuspension", "Rear axle offset", 0f, 0.4f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV1RearSuspension", "Shock ups height", -0.1f, 0.1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV1RearSuspension", "Shock ups offset", -0.1f, 0.1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV1RearSuspension", "Stiffness", 1000f, 50000f, 20000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV1RearSuspension", "Damping", 100f, 10000f, 1000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV1RearSuspension", "Travel", 0.1f, 0.4f, 0.2f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV1RearSuspension", "Shocks size", 1f, 3f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV1RearSuspension", "Shocks", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV1RearSuspension", "Rim", 0f, 0f, 0f, 0, 3, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV1RearSuspension", "Tire", 0f, 0f, 0f, 0, 7, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV1RearSuspension", "Rim size", 0.5f, 1.5f, 1f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV1RearSuspension", "Wheels radius", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV1RearSuspension", "Wheels width", 0.5f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV2FrontSuspension", "Axis width", 0f, 0.2f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV2FrontSuspension", "Stiffness", 1000f, 50000f, 20000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV2FrontSuspension", "Damping", 100f, 10000f, 1000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV2FrontSuspension", "Travel", 0.1f, 0.4f, 0.2f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV2FrontSuspension", "Shocks size", 1f, 3f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV2FrontSuspension", "Shocks", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV2FrontSuspension", "Rim", 0f, 0f, 0f, 0, 3, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV2FrontSuspension", "Tire", 0f, 0f, 0f, 0, 7, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV2FrontSuspension", "Rim size", 0.5f, 1.5f, 1f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV2FrontSuspension", "Wheels radius", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV2FrontSuspension", "Wheels width", 0.5f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV2RearSuspension", "Axis width", 0f, 0.2f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV2RearSuspension", "Rear axle offset", 0f, 0.4f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV2RearSuspension", "Shock ups height", -0.1f, 0.1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV2RearSuspension", "Shock ups offset", -0.1f, 0.1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV2RearSuspension", "Stiffness", 1000f, 50000f, 20000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV2RearSuspension", "Damping", 100f, 10000f, 1000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV2RearSuspension", "Travel", 0.1f, 0.4f, 0.2f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV2RearSuspension", "Shocks size", 1f, 3f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV2RearSuspension", "Shocks", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV2RearSuspension", "Rim", 0f, 0f, 0f, 0, 3, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV2RearSuspension", "Tire", 0f, 0f, 0f, 0, 7, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV2RearSuspension", "Rim size", 0.5f, 1.5f, 1f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV2RearSuspension", "Wheels radius", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV2RearSuspension", "Wheels width", 0.5f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV3FrontSuspension", "Axis width", 0f, 0.2f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV3FrontSuspension", "Stiffness", 1000f, 50000f, 20000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV3FrontSuspension", "Damping", 100f, 10000f, 1000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV3FrontSuspension", "Travel", 0.1f, 0.4f, 0.2f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV3FrontSuspension", "Shocks size", 1f, 3f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV3FrontSuspension", "Shocks", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV3FrontSuspension", "Rim", 0f, 0f, 0f, 0, 3, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV3FrontSuspension", "Tire", 0f, 0f, 0f, 0, 7, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV3FrontSuspension", "Rim size", 0.5f, 1.5f, 1f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV3FrontSuspension", "Wheels radius", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV3FrontSuspension", "Wheels width", 0.5f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV3RearSuspension", "Axis width", 0f, 0.2f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV3RearSuspension", "Rear axle offset", 0f, 0.4f, 0f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV3RearSuspension", "Shock ups height", -0.1f, 0.1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV3RearSuspension", "Shock ups offset", -0.1f, 0.1f, 0f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV3RearSuspension", "Stiffness", 1000f, 50000f, 20000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV3RearSuspension", "Damping", 100f, 10000f, 1000f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV3RearSuspension", "Travel", 0.1f, 0.4f, 0.2f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV3RearSuspension", "Shocks size", 1f, 3f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV3RearSuspension", "Shocks", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV3RearSuspension", "Rim", 0f, 0f, 0f, 0, 3, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV3RearSuspension", "Tire", 0f, 0f, 0f, 0, 7, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV3RearSuspension", "Rim size", 0.5f, 1.5f, 1f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV3RearSuspension", "Wheels radius", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("ATV3RearSuspension", "Wheels width", 0.5f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DirtBikeFrontSuspension", "Stiffness", 1000f, 50000f, 40000f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DirtBikeFrontSuspension", "Damping", 100f, 10000f, 3000f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DirtBikeFrontSuspension", "Travel", 0.1f, 0.5f, 0.4f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DirtBikeFrontSuspension", "Shocks size", 1f, 3f, 1f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DirtBikeFrontSuspension", "Shocks", 0f, 0f, 0f, 0, 2, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DirtBikeFrontSuspension", "Rim", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DirtBikeFrontSuspension", "Tire", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DirtBikeFrontSuspension", "Rim size", 0.5f, 1.1f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DirtBikeFrontSuspension", "Wheels radius", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DirtBikeFrontSuspension", "Wheels width", 0.5f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DirtBikeRearSuspension", "Stiffness", 1000f, 50000f, 40000f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DirtBikeRearSuspension", "Damping", 100f, 10000f, 3000f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DirtBikeRearSuspension", "Travel", 0.1f, 0.5f, 0.4f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DirtBikeRearSuspension", "Shocks size", 1f, 3f, 1f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DirtBikeRearSuspension", "Shocks", 0f, 0f, 0f, 0, 2, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DirtBikeRearSuspension", "Rim", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DirtBikeRearSuspension", "Tire", 0f, 0f, 0f, 0, 2, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DirtBikeRearSuspension", "Rim size", 0.5f, 1.1f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DirtBikeRearSuspension", "Wheels radius", 0.5f, 1.5f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("DirtBikeRearSuspension", "Wheels width", 0.5f, 2f, 1f, 0, 0, 0, true));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("SnowBikeFrontSuspension", "Stiffness", 1000f, 50000f, 40000f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("SnowBikeFrontSuspension", "Damping", 100f, 10000f, 3000f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("SnowBikeFrontSuspension", "Travel", 0.3f, 0.7f, 0.5f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("SnowBikeRearSuspension", "Stiffness", 1000f, 50000f, 40000f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("SnowBikeRearSuspension", "Damping", 100f, 10000f, 3000f, 0, 0, 0, false));
		SuspensionControlLimits.controlLimits.Add(new SuspensionControlLimit("SnowBikeRearSuspension", "Travel", 0.2f, 0.6f, 0.4f, 0, 0, 0, false));
	}

	public static SuspensionControlLimit getLimit(string suspensionName, string name)
	{
		return SuspensionControlLimits.controlLimits.Find((SuspensionControlLimit l) => l.SuspensionName == suspensionName && l.ValueName == name);
	}

	public static List<SuspensionControlLimit> controlLimits = new List<SuspensionControlLimit>();
}
